spring:
  application:
    name: hrbank
  servlet:
    multipart:
      maxFileSize: 10MB         # 파일 하나의 최대 크기
      maxRequestSize: 30MB      # 한 번에 최대 업로드 가능 용량
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate        # 운영은 validate, 개발 초기에는 update/create 사용 가능
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        # default_batch_fetch_size: 100  # 필요시 주석 해제
    open-in-view: false

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace

hrbank:
  storage:
    type: local
    local:
      root-path: .hrbank/storage   # 실제 파일 저장 경로
